name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    name: Deploy
    steps:
      - uses: actions/checkout@v4

      - name: Create Toml File
        run: |
          cat << EOF >> wrangler.toml
          name = "warload-archives-app"
          compatibility_date = "2024-05-02"
          pages_build_output_dir = "./build/client"
          [[r2_buckets]]
          binding = "BUCKET"
          bucket_name = "${{ secrets.R2_BUCKET_NAME }}"
          [vars]
          API_URL = "{{ secrets.API_URL }}"
          EOF

      - name: Deploy
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: warload-archives-app
          directory: ./dist
